routes/web.php
<?php

use App\Http\Controllers\CustomerController;
use App\Http\Controllers\OrderController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('customer', CustomerController::class);
Route::resource('order', OrderController::class);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Customer;

class Order extends Model
{
    use HasFactory;

    public $timestamps = false;
    protected $table = 'order';
    protected $primaryKey = 'order_id';
    protected $fillable = ['customer_id', 'creation_date', 'delivery_address', 'total'];
//    protected $guarded = [];

    public function customer()
    {
//        return $this->hasOne(Customer::class, 'customer_id', 'customer_id');
        return $this->belongsTo(Customer::class, 'customer_id', 'customer_id');
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Models\Customer;
use App\Models\Order;
use Illuminate\Http\Request;
use App\Http\Requests\StoreOrder;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $model = Order::latest('creation_date')->paginate(10);
        return view('order.index', [
            "model" => $model,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = new Order;
        $customers = Customer::all();

        return view('order.create', [
            'customers' => $customers,
            'model' => $model,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreOrder $request)
    {
        /*
        $atributos = request()->validate([
            'customer_id'       => 'required',
            'creation_date'     => 'required',
            'delivery_address'  => 'required',
            'total'             => 'required',
        ]);
        */

//        $atributos['usuariocrea'] = auth()->id();
//        $atributos['usuariomodifica'] = auth()->id();

        Order::create([
            'customer_id'   => $request->customer_id,
            'creation_date' => $request->creation_date,
            'delivery_address'  => $request->delivery_address,
            'total'             => $request->total,
            'usuariocrea'       => aut()->id(),
            'usuariomodifica'   => aut()->id(),
        ]);

//        Order::create(request->all());
//        session()->flash('success', 'Registro creado exitosamente');
        return redirect('order')->with('success', 'Orden registrada exitosamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
//        dd($order);
        $customers = Customer::all();
        //$model = Order::find($order);

        return view('order.edit', [
            'customers' => $customers,
            'model' => $order,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        $atributos = request()->validate([
            'customer_id'       => 'required',
            'creation_date'     => 'required',
            'delivery_address'  => 'required',
            'total'             => 'required',
        ]);
        $atributos['usuariomodifica'] = auth()->id();

        Order::update($atributos);

//        session()->flash('success', 'Registro actualizado exitosamente');
        return redirect('order')->with('success', 'Orden registrada exitosamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        $order->delete();
        return redirect('order')->with('success', 'Registro eliminado exitosamente');
    }
}

resources/views/order/create.blade.php
@extends('layouts.app')

@section('content')

<h1>Crear Orden</h1>

    <form action="{{ url('order') }}" method="POST">
        @csrf
        @include('order.form', ['model' => $model])
    </form>
@endsection

resources/views/order/edit.blade.php
@extends('layouts.app')

@section('content')

<h1>Editar Orden</h1>

    <form action="{{ route('order.update', $model) }}" method="POST">
        @csrf
        @method('PATCH')
        @include('order.form', ['model' => $model])
    </form>

@endsection

resources/views/order/form.blade.php
<div class="form-group">
    <label for="customer_id">Customer</label>
    <select name="customer_id" id="customer_id" class='form-control'>
    @foreach($customers as $value)
        <option value="{{ $value->customer_id }}">{{ old('name', $value->customer_id) }}</option>
    @endforeach
    </select>
    @error('customer_id')
    <p class='alert-danger text-xs mt-1'>{{ $message }}</p>
    @enderror
</div>

<div class="form-group">
    <label for="creation_date">Fecha</label>
    <input type="text" name="creation_date" placeholder="Fecha" value="{{ old('creation_date',$model->creation_date) }}" class='form-control'>
    @error('creation_date')
    <p class='alert-danger text-xs mt-1'>{{ $message }}</p>
    @enderror
</div>
<div class="form-group">
    <label for="delivery_address">Dirección</label>
    <input type="text" name="delivery_address" placeholder="Direccion" value="{{ old('delivery_address', $model->delivery_address) }}" class='form-control'>
    @error('delivery_address')
    <p class='alert-danger text-xs mt-1'>{{ $message }}</p>
    @enderror
</div>
<div class="form-group">
    <label for="total">Total</label>
    <input type="text" name="total" placeholder="Total" value="{{ old('total', $model->total) }}" class='form-control'>
    @error('total')
    <p class='alert-danger text-xs mt-1'>{{ $message }}</p>
    @enderror
</div>
<div class="form-group">
    <input type="submit" value="Enviar" name="enviar" class='form-control btn btn-success'>
</div>

resources/views/order/index.blade.php
@extends('layouts.app')

@section('content')

<h1>Ordenes</h1>

<a href="{{ url('/order/create') }}" class="btn btn-success">Crear</a>

<table class='table table-hover'>

    <tr>
        <th>Order id</th>
        <th>Curstomer id</th>
        <th>creation date</th>
        <th>delivery address</th>
        <th>total</th>
        <th></th>
    </tr>

    @foreach ($model as $value)
    <tr>
        <td>{{ $value->order_id }}</td>
        <td>{{ $value->customer->name }}</td>
        <td>{{ $value->creation_date }}</td>
        <td>{{ $value->delivery_address }}</td>
        <td>{{ $value->total }}</td>
        <td>
            <a href="{{ route('order.edit', $value) }}" class='btn btn-primary'>Editar</a>
            <form action="{{ route('order.destroy', $value) }}" method="post">
                @csrf
                {{ method_field('DELETE') }}
                <input type="submit" value="Eliminar" onclick="return confirm('Realmente desea eliminar este registro?')" class='btn btn-danger'>
            </form>
    </tr>
    @endforeach
</table>

<?= $model->links(); ?>


@endsection